## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import sys
# Import API key
sys.path.append("../")
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df

City_ID          City Country  Max Temp Current Description      Lat  \
0          0       Chapais      CA     55.18     overcast clouds  49.7834   
1          1      San Juan      AR     53.46           clear sky -31.5375   
2          3        Barrow      US     33.82          light rain  71.2906   
3          5      Hermanus      ZA     52.63       broken clouds -34.4187   
4          7  Constitucion      CL     49.77           clear sky -35.3333   
..       ...           ...     ...       ...                 ...      ...   
187      668        Burnie      AU     49.06       broken clouds -41.0667   
188      673      San Luis      AR     48.81          few clouds -33.2950   
189      677          Eina      NO     45.91     overcast clouds  60.6295   
190      679        Juneau      US     51.80       moderate rain  58.3019   
191      685        Emmett      US     53.49           clear sky  43.8735   

          Lng                                 Hotel Name  
0    -74.8492                             Hôtel Opémiska  
1    -68.5364                           Hotel Provincial  
2   -156.7887                             King Eider Inn  
3     19.2345                 Misty Waves Boutique Hotel  
4    -72.4167                Hotel Boutique Las Azucenas  
..        ...                                        ...  
187  145.9167               Beachfront Voyager Motor Inn  
188  -66.3356                              Huarpes Hotel  
189   10.5993                          Skogstad Leirsted  
190 -134.4197  Baranof Downtown, Bw Signature Collection  
191 -116.4993                   Holiday Motel & R.V Park  

[192 rows x 8 columns]

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [11]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City']=='Bose']
vacation_end = vacation_df.loc[vacation_df['City']=='Bose']
vacation_stop1 = vacation_df.loc[vacation_df['City']=='Oga']
vacation_stop2 = vacation_df.loc[vacation_df['City']=='Lasa'] 
vacation_stop3 = vacation_df.loc[vacation_df['City']=='Rothenbach'] 

In [12]:
# 6. Get the latitude-longitude pairs as tuples 
# from each city DataFrame using the to_numpy 
# function and list indexing.
start=pd.DataFrame(vacation_start[["Lat","Lng"]]).to_numpy()[0] 
end=pd.DataFrame(vacation_end[["Lat","Lng"]]).to_numpy()[0]
stop1=pd.DataFrame(vacation_stop1[["Lat","Lng"]]).to_numpy()[0]
stop2=pd.DataFrame(vacation_stop2[["Lat","Lng"]]).to_numpy()[0]
stop3=pd.DataFrame(vacation_stop3[["Lat","Lng"]]).to_numpy()[0]
start,stop1,stop2,stop3

(array([45.4612,  8.0137]),
 array([46.4631, 10.347 ]),
 array([46.6166, 10.7002]),
 array([47.6167,  9.9833]))

In [13]:
# 7. Create a direction layer map using the start and end 
# latitude-longitude pairs,and stop1, stop2, and stop3 as the waypoints.
# The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
itinerary_trip_plan = gmaps.directions_layer(start,end,waypoints=[stop1,stop2,stop3],travel_mode='DRIVING') 
fig.add_layer(itinerary_trip_plan)
fig


Figure(layout=FigureLayout(height='420px'))

In [14]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

City_ID        City Country  Max Temp Current Description      Lat  \
0      486        Bose      IT     55.94           clear sky  45.4612   
1      575         Oga      IT     47.08       broken clouds  46.4631   
2      216        Lasa      IT     54.48    scattered clouds  46.6166   
3      476  Rothenbach      DE     45.25    scattered clouds  47.6167   

       Lng                            Hotel Name  
0   8.0137                  Locanda Borgo Antico  
1  10.3470  QC Terme Bagni di Bormio Bagni Nuovi  
2  10.7002                 Pension Feldgärtenhof  
3   9.9833  Kräuterwirt Rössle Landgasthof Hotel

In [15]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [16]:
# 11a. Add a marker layer for each city to the map.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))